# Generated by Django 6.0.4 on 2026-05-09 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Add your name', max_length=25)),
                ('surname', models.CharField(default='Add your surname', max_length=25)),
                ('age', models.IntegerField(default=18)),
                ('email', models.EmailField(default='Add your email', max_length=254)),
                ('phone_number', models.CharField(default='Add your phone number', max_length=20)),
                ('experience', models.TextField(default='Add your experience')),
                ('education', models.TextField(default='Add your education')),
                ('skills', models.TextField(default='Add your skills')),
                ('salary', models.CharField(default='Add your salary expectation', max_length=20)),
                ('resume_file', models.FileField(blank=True, upload_to='resumes/')),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
