# Generated by Django 6.0.4 on 2026-05-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_company', '0003_alter_review_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('date_tour', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel_company.tourcompany')),
            ],
        ),
    ]
