# Generated by Django 6.0.4 on 2026-05-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('about', models.TextField()),
                ('pages', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('piccture', models.FileField(upload_to='book_pictures/')),
                ('publisher', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
