# Generated by Django 6.0.4 on 2026-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='piccture',
        ),
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='book_pictures/'),
        ),
    ]
