# Generated by Django 6.0.4 on 2026-05-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='views',
            new_name='views_count',
        ),
    ]
