# Generated by Django 6.0.4 on 2026-05-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_company', '0002_alter_service_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
